server:
  port: 8005

spring:
  application:
    name: cloud-payment-hystrix-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springCloud.pojo

eureka:
  client:
    service-url:
     # defaultZone: http://eureka-server1:7001/eureka/
       defaultZone: http://eureka-server1:7001/eureka/,http://eureka-server2:7002/eureka/
  instance:
    #给eureka里面的服务取名
    instance-id: payment8005
    #显示ip
    prefer-ip-address: true
    #心跳检查 30秒默认
    lease-renewal-interval-in-seconds: 1
    #最后一次心跳后等待时间上线
    lease-expiration-duration-in-seconds: 2