server:
  port: 9527

spring:
  application:
    name: cloud-gateway9527
  cloud:
    gateway:
      routes:
        - id: paymentrouth #路由的id,没有固定但要求唯一
         # uri: http://127.0.0.1:8001 #匹配后提供服务的路由 地址
          # 负载均衡轮询
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/** #断言,路径匹配的进行路由
            #这个时间以后才可以访问
            - After=2021-05-30T11:53:46.418+08:00[Asia/Shanghai]
        - id: paymentrouth2
          uri: http://localhost:8002
          predicates:
            - Path=/payment/lb/**


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:7001/eureka/,http://eureka-server2:7002/eureka/



