server:
  port: 7002

eureka:
  instance:
    hostname: eureka-server2
  client:
    #向eureka注册  false表示不注册
    register-with-eureka: true
    #false表示自己就是注册中心
    fetch-registry: true
    service-url:
     defaultZone: http://eureka-server1:7001/eureka/


