server:
  port: 85

spring:
  application:
    name: cloud-payment-order80
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springCloud.pojo


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:7001/eureka/,http://eureka-server2:7002/eureka/

#设置feign客户端超时时间(openFeign默认支持Ribbon)
ribbon:
  #指的是建立连接所用的时间,适用于网路状态正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可以资源所有的时间
  ConnectTimeout: 5000

#feing日志
logging:
  level:
    #feing日志以什么级别监听那个接口
    com.newspringCloud.Feing.PaymentControllerFeing: debug

feign:
  hystrix:
    enabled: true

