server:
  port: 81

spring:
  application:
    name: cloud-payment-order80
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springCloud.pojo


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:7001/eureka/,http://eureka-server2:7002/eureka/